SELECT A.MEMBER_ID, A.MEMBER_NAME, A.GENDER, DATE_FORMAT(A.DATE_OF_BIRTH, '%Y-%m-%d') as DATE_OF_BIRTH
FROM MEMBER_PROFILE A
WHERE A.GENDER = 'W' AND A.TLNO IS NOT NULL AND DATE_FORMAT(A.DATE_OF_BIRTH, '%m') = '03'
ORDER BY A.MEMBER_ID;
