SELECT MONTH(A.START_DATE) AS MONTH, A.CAR_ID, COUNT(A.HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
WHERE MONTH(A.START_DATE) BETWEEN 8 AND 10 
AND A.CAR_ID IN (SELECT CAR_ID
                     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                     WHERE MONTH(START_DATE) BETWEEN 8 AND 10 
                     GROUP BY CAR_ID
                     HAVING COUNT(HISTORY_ID) >= 5)
GROUP BY MONTH(A.START_DATE), A.CAR_ID
ORDER BY MONTH(A.START_DATE), A.CAR_ID DESC
