WITH TEST AS (
    SELECT ID, PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) SIZE
    FROM ECOLI_DATA
)

SELECT ID,
CASE 
WHEN SIZE <= 0.25 THEN 'CRITICAL'
WHEN SIZE > 0.25 AND SIZE <= 0.5 THEN 'HIGH'
WHEN SIZE > 0.5 AND SIZE <= 0.75 THEN 'MEDIUM'
ELSE 'LOW'
END AS COLONY_NAME
FROM TEST
ORDER BY ID;

-- PERCENT_RANK() OVER(정렬) 별칭 (괄호안에 값은 OVER에만 들어갈수 있음)
-- WITH 절을 사용하면 서브쿼리를 어디서나 편리하게 재사용할 수 있어서 좋음
