SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_INS A INNER JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE TIMESTAMPDIFF(SECOND, A.DATETIME, B.DATETIME) < 0 
-- 뒤에서 앞에꺼 뺐을때 차이를 초단위로 구해서 타임스탬프 차이를 계산
ORDER BY A.DATETIME
