SELECT A.USER_ID, A.NICKNAME, CONCAT(A.CITY, ' ', A.STREET_ADDRESS1, ' ', A.STREET_ADDRESS2) AS '전체주소', CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_USER A JOIN USED_GOODS_BOARD B ON B.WRITER_ID = A.USER_ID
GROUP BY A.USER_ID
HAVING COUNT(B.WRITER_ID) >= 3
ORDER BY A.USER_ID DESC;

-- PK값을 기준으로 몇 개 이상 가지고 있는 사람 뽑기 -> GROUP BY 한 후에 HAVING을 써보자!
