SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO A
WHERE A.FAVORITES IN (SELECT MAX(FAVORITES) 
                      FROM REST_INFO 
                      GROUP BY FOOD_TYPE)
GROUP BY A.FOOD_TYPE
ORDER BY A.FOOD_TYPE DESC 
