WITH DOC AS (
    SELECT DR_NAME, DR_ID
    FROM DOCTOR
    WHERE MCDP_CD = 'CS'
), PAT AS (
    SELECT PT_NAME, PT_NO PTN
    FROM PATIENT
)

SELECT APNT_NO, PT_NAME, PT_NO, MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT 
JOIN DOC ON DR_ID = MDDR_ID
JOIN PAT ON PTN = PT_NO
WHERE APNT_CNCL_YN = 'N' AND MCDP_CD = 'CS' AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
ORDER BY APNT_YMD;
