WITH TEST AS(
    SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
    GROUP BY BOOK_ID
)

SELECT A.CATEGORY, SUM(B.TOTAL_SALES) AS TOTAL_SALES
FROM BOOK A JOIN TEST B ON A.BOOK_ID = B.BOOK_ID
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY;

-- 서브쿼리는 확실히 WITH 절을 사용하니 문제가 더 잘풀림
-- WITH 이름 AS 꼭 기억할것 (문법 숙지)
