WITH TEST AS (
    SELECT ID 
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
)

SELECT B.ID
FROM ECOLI_DATA A 
JOIN TEST ON A.PARENT_ID = TEST.ID
JOIN ECOLI_DATA B ON A.ID = B.PARENT_ID
ORDER BY B.ID;

