SELECT A.CAR_ID, A.CAR_TYPE, ROUND(((1 - (C.DISCOUNT_RATE / 100)) * A.DAILY_FEE) * 30, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE  
AND C.DURATION_TYPE LIKE '30%'
WHERE A.CAR_ID NOT IN (SELECT DISTINCT(CAR_ID)
                       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                       WHERE END_DATE LIKE '2022-11%' 
                       OR START_DATE LIKE '2022-11%' 
                       OR(START_DATE < '2022-11-01' AND END_DATE > '2022-11-30'))
                       AND A.CAR_TYPE IN ('세단', 'SUV')
                       AND ROUND(((1 - (C.DISCOUNT_RATE / 100)) * A.DAILY_FEE) * 30, 0) 
                       BETWEEN 500000 AND 2000000
GROUP BY A.CAR_ID
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC;
